package types

// MediaFile describes a file produced by the media tools. Path is an absolute
// path inside the server's configured media output directory.
type MediaFile struct {
	Path      string `json:"path"`
	Filename  string `json:"filename"`
	Ext       string `json:"ext,omitempty"`
	SizeBytes int64  `json:"size_bytes"`
	Title     string `json:"title,omitempty"`
	Duration  string `json:"duration,omitempty"`
	Language  string `json:"language,omitempty"`
}

// DownloadVideoRequest is the input for the download_video tool.
type DownloadVideoRequest struct {
	URL       string `json:"url"`
	Format    string `json:"format,omitempty"`     // optional yt-dlp -f selector override
	AudioOnly bool   `json:"audio_only,omitempty"` // extract best audio as mp3
}

// DownloadVideoResponse is returned by the download_video tool.
type DownloadVideoResponse struct {
	SourceURL string    `json:"source_url"`
	File      MediaFile `json:"file"`
}

// TranscodeRequest is the input for the transcode_media tool. Path must point at
// a file already inside the media output directory (for example one produced by
// download_video).
type TranscodeRequest struct {
	Path       string `json:"path"`
	Format     string `json:"format,omitempty"`      // target container/extension, e.g. mp4, webm, mp3
	VideoCodec string `json:"video_codec,omitempty"` // e.g. libx264, libx265, vp9
	AudioCodec string `json:"audio_codec,omitempty"` // e.g. aac, libmp3lame, libopus
	CRF        int    `json:"crf,omitempty"`         // constant rate factor for x264/x265
	MaxWidth   int    `json:"max_width,omitempty"`   // downscale so width <= max_width
	OutputName string `json:"output_name,omitempty"` // optional output base filename
}

// TranscodeResponse is returned by the transcode_media tool.
type TranscodeResponse struct {
	Input  MediaFile `json:"input"`
	Output MediaFile `json:"output"`
}

// SubtitlesRequest is the input for the download_subtitles tool.
type SubtitlesRequest struct {
	URL           string `json:"url"`
	Language      string `json:"language,omitempty"`       // sub-langs selector, default "en"
	Format        string `json:"format,omitempty"`         // convert subs to this format, default srt
	AutoGenerated bool   `json:"auto_generated,omitempty"` // include auto-generated captions
}

// SubtitlesResponse is returned by the download_subtitles tool.
type SubtitlesResponse struct {
	SourceURL string      `json:"source_url"`
	Files     []MediaFile `json:"files"`
}

// ReadMediaFileRequest is the input for the read_media_file tool. Path must point
// at a file already inside the media output directory, for example a subtitle
// returned by download_subtitles or a file produced by transcode_media.
type ReadMediaFileRequest struct {
	Path     string `json:"path"`
	MaxBytes int64  `json:"max_bytes,omitempty"` // cap on returned bytes; clamped to a server ceiling
}

// CleanSubtitlesRequest is the input for the clean_subtitles tool. Path must
// point at a subtitle/transcript file already inside the media output directory,
// for example one returned by download_subtitles.
type CleanSubtitlesRequest struct {
	Path  string `json:"path"`
	Topic string `json:"topic,omitempty"` // optional focus hint; off-topic material is removed
	Save  bool   `json:"save,omitempty"`  // also write the cleaned text into the media directory
}

// CleanSubtitlesResponse is returned by the clean_subtitles tool. Content is the
// cleaned transcript with intros, outros, ad/sponsor reads, and caption filler
// removed while substantive on-topic content is preserved (not summarized).
type CleanSubtitlesResponse struct {
	SourcePath  string `json:"source_path"`
	Topic       string `json:"topic,omitempty"`
	Model       string `json:"model"`
	Chunks      int    `json:"chunks"`
	InputChars  int    `json:"input_chars"`
	OutputChars int    `json:"output_chars"`
	Content     string `json:"content"`
	SavedPath   string `json:"saved_path,omitempty"`
}

// ReadMediaFileResponse returns the contents of a file in the media directory.
// Encoding is "text" for valid UTF-8 (e.g. subtitles) or "base64" for binary.
type ReadMediaFileResponse struct {
	Path      string `json:"path"`
	Filename  string `json:"filename"`
	Ext       string `json:"ext,omitempty"`
	SizeBytes int64  `json:"size_bytes"`
	Encoding  string `json:"encoding"`
	Content   string `json:"content"`
	Truncated bool   `json:"truncated,omitempty"`
}
