package types

// MediaFile describes a file produced by the media tools. Path is an absolute
// path inside the server's configured media output directory.
type MediaFile struct {
	Path      string `json:"path"`
	Filename  string `json:"filename"`
	Ext       string `json:"ext,omitempty"`
	SizeBytes int64  `json:"size_bytes"`
	Title     string `json:"title,omitempty"`
	Duration  string `json:"duration,omitempty"`
	Language  string `json:"language,omitempty"`
}

// DownloadVideoRequest is the input for the download_video tool.
type DownloadVideoRequest struct {
	URL       string `json:"url"`
	Format    string `json:"format,omitempty"`     // optional yt-dlp -f selector override
	AudioOnly bool   `json:"audio_only,omitempty"` // extract best audio as mp3
}

// DownloadVideoResponse is returned by the download_video tool.
type DownloadVideoResponse struct {
	SourceURL string    `json:"source_url"`
	File      MediaFile `json:"file"`
}

// TranscodeRequest is the input for the transcode_media tool. Path must point at
// a file already inside the media output directory (for example one produced by
// download_video).
type TranscodeRequest struct {
	Path       string `json:"path"`
	Format     string `json:"format,omitempty"`      // target container/extension, e.g. mp4, webm, mp3
	VideoCodec string `json:"video_codec,omitempty"` // e.g. libx264, libx265, vp9
	AudioCodec string `json:"audio_codec,omitempty"` // e.g. aac, libmp3lame, libopus
	CRF        int    `json:"crf,omitempty"`         // constant rate factor for x264/x265
	MaxWidth   int    `json:"max_width,omitempty"`   // downscale so width <= max_width
	OutputName string `json:"output_name,omitempty"` // optional output base filename
}

// TranscodeResponse is returned by the transcode_media tool.
type TranscodeResponse struct {
	Input  MediaFile `json:"input"`
	Output MediaFile `json:"output"`
}

// SubtitlesRequest is the input for the download_subtitles tool.
type SubtitlesRequest struct {
	URL           string `json:"url"`
	Language      string `json:"language,omitempty"`       // sub-langs selector, default "en"
	Format        string `json:"format,omitempty"`         // convert subs to this format, default srt
	AutoGenerated bool   `json:"auto_generated,omitempty"` // include auto-generated captions
}

// SubtitlesResponse is returned by the download_subtitles tool.
type SubtitlesResponse struct {
	SourceURL string      `json:"source_url"`
	Files     []MediaFile `json:"files"`
}
