package types

// MediaFile describes a file produced by the media tools. Path is an absolute
// path inside the server's configured media output directory.
type MediaFile struct {
	Path      string `json:"path"`
	Filename  string `json:"filename"`
	Ext       string `json:"ext,omitempty"`
	SizeBytes int64  `json:"size_bytes"`
	Title     string `json:"title,omitempty"`
	Duration  string `json:"duration,omitempty"`
	Language  string `json:"language,omitempty"`
}

// DownloadVideoRequest is the input for the download_video tool.
type DownloadVideoRequest struct {
	URL       string `json:"url"`
	Format    string `json:"format,omitempty"`     // optional yt-dlp -f selector override
	AudioOnly bool   `json:"audio_only,omitempty"` // extract best audio as mp3
}

// DownloadVideoResponse is returned by the download_video tool.
type DownloadVideoResponse struct {
	SourceURL string    `json:"source_url"`
	File      MediaFile `json:"file"`
}

// TranscodeRequest is the input for the transcode_media tool. Path must point at
// a file already inside the media output directory (for example one produced by
// download_video).
type TranscodeRequest struct {
	Path       string `json:"path"`
	Format     string `json:"format,omitempty"`      // target container/extension, e.g. mp4, webm, mp3
	VideoCodec string `json:"video_codec,omitempty"` // e.g. libx264, libx265, vp9
	AudioCodec string `json:"audio_codec,omitempty"` // e.g. aac, libmp3lame, libopus
	CRF        int    `json:"crf,omitempty"`         // constant rate factor for x264/x265
	MaxWidth   int    `json:"max_width,omitempty"`   // downscale so width <= max_width
	OutputName string `json:"output_name,omitempty"` // optional output base filename
}

// TranscodeResponse is returned by the transcode_media tool.
type TranscodeResponse struct {
	Input  MediaFile `json:"input"`
	Output MediaFile `json:"output"`
}

// SubtitlesRequest is the input for the download_subtitles tool.
type SubtitlesRequest struct {
	URL           string `json:"url"`
	Language      string `json:"language,omitempty"`       // sub-langs selector, default "en"
	Format        string `json:"format,omitempty"`         // convert subs to this format, default srt
	AutoGenerated bool   `json:"auto_generated,omitempty"` // include auto-generated captions
}

// SubtitlesResponse is returned by the download_subtitles tool.
type SubtitlesResponse struct {
	SourceURL string      `json:"source_url"`
	Files     []MediaFile `json:"files"`
}

// ReadMediaFileRequest is the input for the read_media_file tool. Path must point
// at a file already inside the media output directory, for example a subtitle
// returned by download_subtitles or a file produced by transcode_media.
type ReadMediaFileRequest struct {
	Path     string `json:"path"`
	MaxBytes int64  `json:"max_bytes,omitempty"` // cap on returned bytes; clamped to a server ceiling
}

// CleanSubtitlesRequest is the input for the clean_subtitles tool. Path must
// point at a subtitle/transcript file already inside the media output directory,
// for example one returned by download_subtitles.
type CleanSubtitlesRequest struct {
	Path  string `json:"path"`
	Topic string `json:"topic,omitempty"` // optional focus hint; off-topic material is removed
	Save  bool   `json:"save,omitempty"`  // also write the cleaned text into the media directory
}

// CleanSubtitlesResponse is returned by the clean_subtitles tool. Content is the
// cleaned transcript with intros, outros, ad/sponsor reads, and caption filler
// removed while substantive on-topic content is preserved (not summarized).
type CleanSubtitlesResponse struct {
	SourcePath  string `json:"source_path"`
	Topic       string `json:"topic,omitempty"`
	Model       string `json:"model"`
	Chunks      int    `json:"chunks"`
	InputChars  int    `json:"input_chars"`
	OutputChars int    `json:"output_chars"`
	Content     string `json:"content"`
	SavedPath   string `json:"saved_path,omitempty"`
}

// ProbeMediaRequest is the input for the probe_media tool. Path must point at a
// file already inside the media output directory, for example one produced by
// download_video or transcode_media.
type ProbeMediaRequest struct {
	Path string `json:"path"`
}

// ProbeStream describes a single container stream reported by ffprobe. Only the
// fields relevant to the stream's type are populated (resolution for video,
// channels/sample rate for audio, language for subtitles).
type ProbeStream struct {
	Index      int    `json:"index"`
	Type       string `json:"type"` // video, audio, subtitle, data, attachment
	Codec      string `json:"codec,omitempty"`
	Profile    string `json:"profile,omitempty"`
	Width      int    `json:"width,omitempty"`
	Height     int    `json:"height,omitempty"`
	FrameRate  string `json:"frame_rate,omitempty"`  // simplified, e.g. "30" or "29.97"
	Channels   int    `json:"channels,omitempty"`    // audio
	SampleRate string `json:"sample_rate,omitempty"` // audio, Hz
	Language   string `json:"language,omitempty"`
	Title      string `json:"title,omitempty"`
}

// ProbeMediaResponse is returned by the probe_media tool. It exposes container
// and per-stream metadata so a caller can decide how (or whether) to transcode a
// file without downloading or re-encoding it first.
type ProbeMediaResponse struct {
	Path          string        `json:"path"`
	Filename      string        `json:"filename"`
	FormatName    string        `json:"format_name,omitempty"`
	FormatLong    string        `json:"format_long_name,omitempty"`
	Duration      string        `json:"duration,omitempty"`       // seconds, as reported by ffprobe
	DurationHuman string        `json:"duration_human,omitempty"` // H:MM:SS or M:SS
	SizeBytes     int64         `json:"size_bytes"`
	BitRate       string        `json:"bit_rate,omitempty"` // bits per second
	StreamCount   int           `json:"stream_count"`
	Streams       []ProbeStream `json:"streams"`
}

// ReadMediaFileResponse returns the contents of a file in the media directory.
// Encoding is "text" for valid UTF-8 (e.g. subtitles) or "base64" for binary.
type ReadMediaFileResponse struct {
	Path      string `json:"path"`
	Filename  string `json:"filename"`
	Ext       string `json:"ext,omitempty"`
	SizeBytes int64  `json:"size_bytes"`
	Encoding  string `json:"encoding"`
	Content   string `json:"content"`
	Truncated bool   `json:"truncated,omitempty"`
}
